package scanner;

public enum TokenType {
	NUMBER, ID, ILLEGAL,
    AND, ARRAY, BEGIN, DIV, DO, ELSE, END, FUNCTION, IF, INTEGER, MOD, NOT, OF, OR,
    PROCEDURE, PROGRAM, REAL, THEN, VAR, WHILE, SEMICOLON, COMMA, PERIOD, COLON,
    LSQBRACKET, RSQBRACKET, LPARENTHESES, RPARENTHESES, PLUS, MINUS, EQUAL, NOTEQUAL,
    LESSTHAN, LESSTHANOREQUALTO, GREATERTHAN, GREATERTHANOREQUALTO, ASTERISK, SLASH, BECOMES,
}